import { TypeSafeDiceRoller } from './TypeSafeDiceRoller';

export function TypeSafeDiceRollerDemo() {
  return (
    <div style={{ padding: '20px', maxWidth: '600px', margin: '0 auto' }}>
      <h1>🎲 Type-Safe API Demo</h1>
      <p style={{ marginBottom: '20px', color: '#666' }}>
        This component uses the new type-safe API generated by Orval from OpenAPI specs.
        All types are automatically synchronized between backend and frontend.
      </p>
      <TypeSafeDiceRoller />
      
      <div style={{ marginTop: '30px', padding: '15px', background: '#f5f5f5', borderRadius: '4px' }}>
        <h3>✅ Type Safety Features</h3>
        <ul>
          <li>Request/response types generated from Zod schemas</li>
          <li>Compile-time validation of API calls</li>
          <li>Auto-complete for all API parameters</li>
          <li>No manual type definitions needed</li>
        </ul>
      </div>
    </div>
  );
}
