/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * D&D Battle Manager API
 * Type-safe API for D&D 5e battle management
 * OpenAPI spec version: 1.0.0
 */
export type PostApiDiceRollBody = {
  /** Dice roll expression (e.g., 2d6+3, 1d20, 2d20kh1) */
  notation: string;
  /** Additional modifier to add to the roll */
  modifier?: number;
  /** Optional description for the roll */
  description?: string;
};

export type PostApiDiceRoll200 = {
  id: string;
  notation: string;
  rolls: number[];
  total: number;
  modifier: number;
  description?: string;
  timestamp: number;
};

export type PostApiDiceRoll400 = {
  error: string;
};

